export const WELFARES_FILTER_LIST = [
  { value: "timelapse", name: "자율근무제" },
  { value: "home", name: "재택근무" },
  { value: "pregnant_woman", name: "출산지원" },
  { value: "child_friendly", name: "육아지원" },
  { value: "child_care", name: "사내어린이집" },
  { value: "school", name: "자녀학자금" },
  { value: "monitor_heart", name: "건강검진" },
  { value: "wallet", name: "대출지원" },
  { value: "restaurant", name: "사내식당" },
  { value: "local_cafe", name: "사내카페" },
  { value: "redeem", name: "복지포인트" },
  { value: "menu_book", name: "도서비지원" },
  { value: "trending_up", name: "스톡옵션" },
  { value: "important_devices", name: "최신형장비" },
  { value: "directions_bus_filled", name: "통근버스" },
];

export const WELFARES_ICONS = [
  { value: "home", name: "재택근무" },
  { value: "timelapse", name: "자율출퇴근" },
  { value: "forest", name: "휴가" },
  { value: "business", name: "거점오피스" },
  { value: "monitor_heart", name: "건강검진" },
  { value: "medication", name: "의료보험지원" },
  { value: "pregnant_woman", name: "출산지원" },
  { value: "child_friendly", name: "아동육아" },
  { value: "directions_bus_filled", name: "통근버스" },
  { value: "school", name: "학자금지원" },
  { value: "group_work", name: "사내동호회" },
  { value: "restaurant", name: "사내식당" },
  { value: "restaurant_menu", name: "식사비지원" },
  { value: "local_cafe", name: "사내카페" },
  { value: "library_books", name: "사내도서관" },
  { value: "local_hospital", name: "사내병원" },
  { value: "fitness_center", name: "헬스장" },
  { value: "sports_handball", name: "운동비지원" },
  { value: "child_care", name: "어린이집" },
  { value: "redeem", name: "복지포인트" },
  { value: "wallet", name: "금융지원" },
  { value: "important_devices", name: "최신 장비" },
  { value: "trending_up", name: "스톡옵션" },
  { value: "price_check", name: "사이닝보너스" },
  { value: "connect_without_contact", name: "외부교육지원" },
  { value: "language", name: "어학지원" },
  { value: "menu_book", name: "도서비" },
  { value: "hotel", name: "수면실" },
  { value: "local_taxi", name: "택시" },
  { value: "connect_without_contact", name: "교육참가지원" },
  { value: "diversity_2", name: "경조사" },
];
